[package]
name = "models"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
uuid = { workspace = true }
sqlx = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

rust_decimal = "1.37.1"
