[package]
name = "api"
version = "0.1.0"
edition.workspace = true

[dependencies]
sqlx = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
rust_decimal = { workspace = true, features = ["serde"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

tokio = { version = "1", features = ["full"] }

chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"


anyhow = { version = "1.0" }
cookie = "0.18.1"
jsonwebtoken = "9.3.1"
axum = { version = "0.8.3", optional = true }
tonic = { version = "0.13.0", optional = true }
bcrypt = "0.17.0"
ring = "0.17.14"
thiserror = "2.0.12"
validator = { version = "0.20.0", features = ["derive"] }
aes-gcm = { version = "0.10.3" }
hex = "0.4.3"
sha3 = { version = "0.10.8" }
[features]
default = ["rest"]
rest = ["axum"]
grpc = ["tonic"]
