[package]
name = "parser"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

calamine = "0.26.1"
csv = "1.3.1"
rust_xlsxwriter = "0.84.2"
bytes = "1.10.1"
